name: Publish to PyPI (Trusted Publishing)

on:
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    # IMPORTANT: this must match the environment name you registered on PyPI
    environment: pypi
    permissions:
      id-token: write     # <-- REQUIRED for PyPI Trusted Publishing (OIDC)
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build sdist and wheel
        run: |
          python -m pip install --upgrade pip build
          python -m build

      # Publish to PyPI using OIDC (no API token needed)
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          # repository-url: https://upload.pypi.org/legacy/  # default; omit unless using TestPyPI
